# docker-compose.yml
version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    links:
      - "api"

  api:
    build:
      context: ./api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4200:4200"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
