# docker-compose.yml
version: "3"
services:
  client:
    build:
      context: ./client
    links:
      - "api"

  api:
    build:
      context: ./api
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      context: ./db
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - client
      - api
